@base_url = https://localhost:7015/api/tarefa

### Listar Tarefas ###
GET {{base_url}}/listar

### Criar Tarefa ###
POST {{base_url}}/cadastrar
Content-Type: application/json

{
  "Titulo": "Compraaaaaaaa",
  "Descricao": "1. Fazer UMA lista de compras: pão, leite, ovos, frutas, vegetais",
  "Status": "Não Iniciada",
  "CategoriaId": 4
}

### Buscar Tarefa ###


### Alterar ###

PATCH {{base_url}}/alterar/12


### Listar Não Concluídas ###
GET {{base_url}}/listarNaoConcluidas


### Listar Concluídas
GET {{base_url}}/listarConcluidas


